name: todo_list
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get:
  get_storage:
  isar:
  isar_flutter_libs:
  path_provider:
  http:
  shared_preferences:
  image_picker:


dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator:
  build_runner:


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

